#!/usr/bin/env node

"use strict";

var startup_actor = null;
if (process.argv.length === 3) {
  startup_actor = process.argv[2];
}

let debug = false;
let spew = undefined;
if (debug) {
  spew = function(name, pat, data) { console.log(name, pat, data)};
}

let server = require("./server.js");

server.listen(8080, spew, startup_actor);
